services:
  - type: web
    name: egyptian-house-price-app
    runtime: python
    rootDir: egyptian-house-price-app-redesigned/egyptian-house-price-app
    buildCommand: pip install -r backend/requirements.txt && npm --prefix frontend install && npm --prefix frontend run build
    startCommand: gunicorn --chdir backend app:app
    plan: free